@startuml
'https://plantuml.com/sequence-diagram

actor "External Service" as ES
participant "Order Administration" as OA
database "Write Model" as WM
database "Read Model" as RM
queue "Event Storage" as ESG

ES -> OA: CancellationOrderCommand\n1: RequestId\n2: OrderId\n3: Reason
OA -> OA: transform to Java Domain
OA -> RM: get order by OrderId
OA -> OA: change status to "CANCELLED"
OA -> WM: update order
OA -> OA: transform to Avro
OA -> ESG: OrderCancelledEvent\n1: RequestId\n2: OrderId

@enduml