@startuml
'https://plantuml.com/sequence-diagram

actor "External Service" as ES
participant "Order Administration" as OA
database "Write Model" as WM
database "Read Model" as RM
queue "Event Storage" as ESG

ES -> OA: PaymentOrderModificationCommand\n1: RequestId\n2: OrderId\n3: Set<ProductIds>\n4: ShippingProfile
OA -> OA: transform to Java Domain
OA -> RM: get order by OrderId
OA -> OA: check order status in allowed for modification
OA -> OA: append Set<ProductIds> method
OA -> WM: update order
OA -> OA: transform to Avro
OA -> ESG: ProductOrderModifiedEvent\n1: RequestId\n2: OrderId\n3: Set<ProductIds>\n4: ShippingProfile

@enduml