@startuml
'https://plantuml.com/sequence-diagram

queue "Event Storage" as ESG
participant "Order Administration" as OA
database "Write Model" as WM
database "Read Model" as RM

ESG -> OA: OrderReceivedEvent\n1: RequestId\n2: OrderId
OA -> OA: transform to Java Domain
OA -> RM: get order by OrderId
OA -> OA: change status to "COMPLETED"
OA -> OA: change sub status to "RECEIVED"
OA -> WM: update order
OA -> OA: transform to Avro
OA -> ESG: OrderCompletedEvent\n1: RequestId\n2: OrderId

@enduml