@startuml
'https://plantuml.com/sequence-diagram

actor "Client" as C
participant "Order Administration" as OA
database "Read Model" as RM
queue "Event Storage" as ESG

C -> OA: ShowOrderHistoryQuery\n1: AccountId
OA -> OA: transform to Java Domain
OA -> RM: get orders by AccountId
OA -> OA: transform to Avro
OA -> ESG: ShownOrderHistoryEvent

@enduml