@startuml
'https://plantuml.com/sequence-diagram

actor "Client" as C
participant "Order Administration" as OA
database "Read Model" as RM

C -> OA: ShowOrderHistoryQuery\n1: AccountId
OA -> OA: transform to Java Domain
OA -> RM: get orders by AccountId
OA -> OA: transform to Json
OA -> C: ShownOrderHistoryEvent

@enduml